### ISSUE TITLE
I got this error when I am going to run the probject

### ISSUE THREAD

**Issue by rosegun38** [fbsamples/f8app#62]
I followed every step of Readme, and I tried both Android & iOS platform, I got the same error.

> this._nativeModule.addListener is not a function.(In 'this._nativeModule.addListener(eventType)',
> 
> 'this._nativeModule.addListener' is undefined)
> ![img_0443](https://cloud.githubusercontent.com/assets/1725675/15703523/5f2c1db6-2818-11e6-891b-3140581ed57a.PNG)

can anybody help me for this error?

**Comment by xu-duqing** [comment]
你是不是启错服务了？

**Comment by aldrinarciga** [comment]
I am having the same problem. Any idea?

**Comment by flyingzl** [comment]
@rosegun38 Maybe you should upgrade your `react-native-cli`.. try `npm install react-native-cli -g `

**Comment by alanwilhelm** [comment]
anything new here?

**Comment by MillerDix** [comment]
$ sudo lsof -n -i4TCP:8081 | grep LISTEN 
$ kill -9 <node id> 
This should work..

**Comment by antonellil** [comment]
I am having this same problem using RN v0.27.2 but not with v0.25.1.

Any help would be appreciated

**Comment by Bob1993** [comment]
The server opened may not belong to the project.

**Comment by n8stowell82** [comment]
please see my comment here -> [https://github.com/facebook/react-native/issues/8025#issuecomment-236226110](url)

this is how I fixed my project

**Comment by itinance** [comment]
@n8stowell82 : this link is broken

**Comment by n8stowell82** [comment]
that is strange.  Anyway here is the link to the issue, and my comment is the last one. sorry about that!
[https://github.com/facebook/react-native/issues/8025](url)

**Comment by amaanmemon** [comment]
@n8stowell82: I am using react-native --version: 0.34.0
still facing the same issue, please find my code below.
```
const myModuleEvt = new NativeEventEmitter(NativeModules.SubcribeClass);
alert("STEP 1");

var subs = myModuleEvt.addListener('PReceiver', (data) => {
     alert("STEP 2")
     console.log(data)
});
```
Shows me an error as this._native.addListener is not a function. please help me with same, Thanks!
