### ISSUE TITLE
react-native run-ios build error.

### ISSUE THREAD

**Issue by lusecond** [fbsamples/f8app#95]
Found Xcode workspace F8v2.xcworkspace
Launching iPhone 6 (8.4)...
Building using "xcodebuild -workspace F8v2.xcworkspace -scheme F8v2 -destination id=9DE497D2-604C-4D78-B631-F93E3396B3E4 -derivedDataPath build"
2016-07-12 17:54:00.188 xcodebuild[10205:3724121] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
User defaults from command line:
    IDEDerivedDataPathOverride = /var/IOS/f8app/ios/build

2016-07-12 17:54:00.527 xcodebuild[10205:3724121] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7702/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo={NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7fc6d37e7240>
Method:   -loadRepositories
Thread:   <NSThread: 0x7fc6d350a6e0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
=== BUILD TARGET BVLinearGradient OF PROJECT BVLinearGradient WITH CONFIGURATION Debug ===

Check dependencies

CompileC /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.o BVLinearGradient/BVLinearGradientManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/IOS/f8app/node_modules/react-native-linear-gradient
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0@global/bin:/Users/wuyuan/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/git/bin:/Users/wuyuan/Documents/adt/sdk/tools:/Users/wuyuan/Documents/adt/sdk/platform-tools:/Users/wuyuan/.rvm/bin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=87 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/var/IOS/f8app/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/IOS/f8app/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=7.0 -iquote /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-generated-files.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-own-target-headers.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-all-target-headers.hmap -iquote /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-project-headers.hmap -I/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/var/IOS/f8app/node_modules/react-native-linear-gradient/../../React -I../react-native/React -I../react-native/React/Base -I../react-native/React/Executors -I../react-native/React/Layout -I../react-native/React/Modules -I../react-native/React/Profiler -I../react-native/React/Views -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/DerivedSources/x86_64 -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/DerivedSources -F/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.d --serialize-diagnostics /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.dia -c /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.m -o /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.o
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.m:1:
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.h:1:
In file included from ../react-native/React/Views/RCTViewManager.h:12:
../react-native/React/Base/RCTBridgeModule.h:222:14: error: expected '>'
- (NSArray<id<RCTBridgeMethod>> *)methodsToExport;
             ^
../react-native/React/Base/RCTBridgeModule.h:222:14: error: expected ')'
../react-native/React/Base/RCTBridgeModule.h:222:3: note: to match this '('
- (NSArray<id<RCTBridgeMethod>> *)methodsToExport;
  ^
../react-native/React/Base/RCTBridgeModule.h:222:1: error: interface type 'NSArray'
      cannot be returned by value; did you forget * in 'NSArray'?
- (NSArray<id<RCTBridgeMethod>> *)methodsToExport;
^
../react-native/React/Base/RCTBridgeModule.h:231:26: error: expected '>'
- (NSDictionary<NSString *, id> *)constantsToExport;
                         ^
../react-native/React/Base/RCTBridgeModule.h:231:27: error: expected ')'
- (NSDictionary<NSString *, id> *)constantsToExport;
                          ^
../react-native/React/Base/RCTBridgeModule.h:231:3: note: to match this '('
- (NSDictionary<NSString *, id> *)constantsToExport;
  ^
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.m:1:
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.h:1:
In file included from ../react-native/React/Views/RCTViewManager.h:13:
In file included from ../react-native/React/Base/RCTConvert.h:18:
In file included from ../react-native/React/Base/RCTLog.h:12:
../react-native/React/Base/RCTAssert.h:124:76: error: expected '>'
  ...NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSString *, id...
                                                                     ^
../react-native/React/Base/RCTAssert.h:124:76: error: interface type 'NSArray' cannot
      be passed by value; did you forget * in 'NSArray'?
RCT_EXTERN NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSS...
                                                                           ^
                                                       *
../react-native/React/Base/RCTAssert.h:124:76: error: expected ')'
../react-native/React/Base/RCTAssert.h:124:36: note: to match this '('
RCT_EXTERN NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSS...
                                   ^
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.m:1:
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.h:1:
In file included from ../react-native/React/Views/RCTViewManager.h:13:
../react-native/React/Base/RCTConvert.h:97:20: error: expected '>'
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
                   ^
../react-native/React/Base/RCTConvert.h:97:21: error: expected ')'
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
                    ^
../react-native/React/Base/RCTConvert.h:97:3: note: to match this '('
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:98:21: error: expected '>'
+ (NSArray<NSString *> *)NSStringArray:(id)json;
                    ^
../react-native/React/Base/RCTConvert.h:98:22: error: expected ')'
+ (NSArray<NSString *> *)NSStringArray:(id)json;
                     ^
../react-native/React/Base/RCTConvert.h:98:3: note: to match this '('
+ (NSArray<NSString *> *)NSStringArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:99:19: error: expected '>'
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
                  ^
../react-native/React/Base/RCTConvert.h:99:19: error: expected ')'
../react-native/React/Base/RCTConvert.h:99:3: note: to match this '('
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:99:1: error: interface type 'NSArray' cannot be
      returned by value; did you forget * in 'NSArray'?
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
^
../react-native/React/Base/RCTConvert.h:100:25: error: expected '>'
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
                        ^
../react-native/React/Base/RCTConvert.h:100:26: error: expected ')'
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
                         ^
../react-native/React/Base/RCTConvert.h:100:3: note: to match this '('
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:101:18: error: expected '>'
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
                 ^
../react-native/React/Base/RCTConvert.h:101:19: error: expected ')'
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
                  ^
../react-native/React/Base/RCTConvert.h:101:3: note: to match this '('
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

CompileC /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradient.o BVLinearGradient/BVLinearGradient.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/IOS/f8app/node_modules/react-native-linear-gradient
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0@global/bin:/Users/wuyuan/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/git/bin:/Users/wuyuan/Documents/adt/sdk/tools:/Users/wuyuan/Documents/adt/sdk/platform-tools:/Users/wuyuan/.rvm/bin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=87 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/var/IOS/f8app/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/IOS/f8app/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=7.0 -iquote /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-generated-files.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-own-target-headers.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-all-target-headers.hmap -iquote /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/BVLinearGradient-project-headers.hmap -I/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/var/IOS/f8app/node_modules/react-native-linear-gradient/../../React -I../react-native/React -I../react-native/React/Base -I../react-native/React/Executors -I../react-native/React/Layout -I../react-native/React/Modules -I../react-native/React/Profiler -I../react-native/React/Views -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/DerivedSources/x86_64 -I/var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/DerivedSources -F/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradient.d --serialize-diagnostics /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradient.dia -c /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.m -o /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradient.o
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.m:1:
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.h:2:
In file included from ../react-native/React/Views/RCTView.h:15:
../react-native/React/Views/RCTComponent.h:30:14: error: expected '>'
- (NSArray<id<RCTComponent>> *)reactSubviews;
             ^
../react-native/React/Views/RCTComponent.h:30:14: error: expected ')'
../react-native/React/Views/RCTComponent.h:30:3: note: to match this '('
- (NSArray<id<RCTComponent>> *)reactSubviews;
  ^
../react-native/React/Views/RCTComponent.h:30:1: error: interface type 'NSArray' cannot
      be returned by value; did you forget * in 'NSArray'?
- (NSArray<id<RCTComponent>> *)reactSubviews;
^
../react-native/React/Views/RCTComponent.h:44:39: error: expected '>'
- (void)didSetProps:(NSArray<NSString *> *)changedProps;
                                      ^
../react-native/React/Views/RCTComponent.h:44:40: error: expected ')'
- (void)didSetProps:(NSArray<NSString *> *)changedProps;
                                       ^
../react-native/React/Views/RCTComponent.h:44:21: note: to match this '('
- (void)didSetProps:(NSArray<NSString *> *)changedProps;
                    ^
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.m:2:
In file included from ../react-native/React/Base/RCTConvert.h:18:
In file included from ../react-native/React/Base/RCTLog.h:12:
../react-native/React/Base/RCTAssert.h:124:76: error: expected '>'
  ...NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSString *, id...
                                                                     ^
../react-native/React/Base/RCTAssert.h:124:76: error: interface type 'NSArray' cannot
      be passed by value; did you forget * in 'NSArray'?
RCT_EXTERN NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSS...
                                                                           ^
                                                       *
../react-native/React/Base/RCTAssert.h:124:76: error: expected ')'
../react-native/React/Base/RCTAssert.h:124:36: note: to match this '('
RCT_EXTERN NSString *RCTFormatError(NSString *message, NSArray<NSDictionary<NSS...
                                   ^
In file included from /var/IOS/f8app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.m:2:
../react-native/React/Base/RCTConvert.h:97:20: error: expected '>'
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
                   ^
../react-native/React/Base/RCTConvert.h:97:21: error: expected ')'
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
                    ^
../react-native/React/Base/RCTConvert.h:97:3: note: to match this '('
+ (NSArray<NSArray *> *)NSArrayArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:98:21: error: expected '>'
+ (NSArray<NSString *> *)NSStringArray:(id)json;
                    ^
../react-native/React/Base/RCTConvert.h:98:22: error: expected ')'
+ (NSArray<NSString *> *)NSStringArray:(id)json;
                     ^
../react-native/React/Base/RCTConvert.h:98:3: note: to match this '('
+ (NSArray<NSString *> *)NSStringArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:99:19: error: expected '>'
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
                  ^
../react-native/React/Base/RCTConvert.h:99:19: error: expected ')'
../react-native/React/Base/RCTConvert.h:99:3: note: to match this '('
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:99:1: error: interface type 'NSArray' cannot be
      returned by value; did you forget * in 'NSArray'?
+ (NSArray<NSArray<NSString *> *> *)NSStringArrayArray:(id)json;
^
../react-native/React/Base/RCTConvert.h:100:25: error: expected '>'
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
                        ^
../react-native/React/Base/RCTConvert.h:100:26: error: expected ')'
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
                         ^
../react-native/React/Base/RCTConvert.h:100:3: note: to match this '('
+ (NSArray<NSDictionary *> *)NSDictionaryArray:(id)json;
  ^
../react-native/React/Base/RCTConvert.h:101:18: error: expected '>'
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
                 ^
../react-native/React/Base/RCTConvert.h:101:19: error: expected ')'
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
                  ^
../react-native/React/Base/RCTConvert.h:101:3: note: to match this '('
+ (NSArray<NSURL *> *)NSURLArray:(id)json;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

=== BUILD TARGET Bolts OF PROJECT Pods WITH CONFIGURATION Debug ===
Check dependencies

CompileC /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Objects-normal/x86_64/BFAppLinkNavigation.o Bolts/Bolts/iOS/BFAppLinkNavigation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/IOS/f8app/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0@global/bin:/Users/wuyuan/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/git/bin:/Users/wuyuan/Documents/adt/sdk/tools:/Users/wuyuan/Documents/adt/sdk/platform-tools:/Users/wuyuan/.rvm/bin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=87 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/var/IOS/f8app/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/IOS/f8app/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Bolts-generated-files.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Bolts-own-target-headers.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Bolts-all-target-headers.hmap -iquote /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Bolts-project-headers.hmap -I/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator/Bolts/include -I/var/IOS/f8app/ios/Pods/Headers/Private -I/var/IOS/f8app/ios/Pods/Headers/Private/Bolts -I/var/IOS/f8app/ios/Pods/Headers/Public -I/var/IOS/f8app/ios/Pods/Headers/Public/Bolts -I/var/IOS/f8app/ios/Pods/Headers/Public/CodePush -I/var/IOS/f8app/ios/Pods/Headers/Public/FBSDKCoreKit -I/var/IOS/f8app/ios/Pods/Headers/Public/FBSDKLoginKit -I/var/IOS/f8app/ios/Pods/Headers/Public/FBSDKShareKit -I/var/IOS/f8app/ios/Pods/Headers/Public/React -I/var/IOS/f8app/ios/Pods/Headers/Public/react-native-fbsdk -I/var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/DerivedSources/x86_64 -I/var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/DerivedSources -F/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator/Bolts -include /var/IOS/f8app/ios/Pods/Target\ Support\ Files/Bolts/Bolts-prefix.pch -MMD -MT dependencies -MF /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Objects-normal/x86_64/BFAppLinkNavigation.d --serialize-diagnostics /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Objects-normal/x86_64/BFAppLinkNavigation.dia -c /var/IOS/f8app/ios/Pods/Bolts/Bolts/iOS/BFAppLinkNavigation.m -o /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Objects-normal/x86_64/BFAppLinkNavigation.o

=== BUILD TARGET RCTFBSDK OF PROJECT RCTFBSDK WITH CONFIGURATION Debug ===
Check dependencies

CompileC /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareDialog.o RCTFBSDK/share/RCTFBSDKShareDialog.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/IOS/f8app/node_modules/react-native-fbsdk/iOS
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0/bin:/Users/wuyuan/.rvm/gems/ruby-2.3.0@global/bin:/Users/wuyuan/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/local/sbib:/usr/local/opt/php55/sbin:/usr/local/opt/php55/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/git/bin:/Users/wuyuan/Documents/adt/sdk/tools:/Users/wuyuan/Documents/adt/sdk/platform-tools:/Users/wuyuan/.rvm/bin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=87 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/var/IOS/f8app/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/IOS/f8app/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=7.0 -iquote /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/RCTFBSDK-generated-files.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/RCTFBSDK-own-target-headers.hmap -I/var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/RCTFBSDK-all-target-headers.hmap -iquote /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/RCTFBSDK-project-headers.hmap -I/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../react -I../../react/dist -I../../react/lib -I../../react-native/React -I../../react-native/React/Base -I../../react-native/React/Executors -I../../react-native/React/Layout -I../../react-native/React/Modules -I../../react-native/React/Profiler -I../../react-native/React/Views -I../../../ios -I../../../ios/build -I../../../ios/F8v2 -I../../../ios/F8v2.xcworkspace -I../../../ios/F8v2Tests -I../../../ios/Pods -I../../../ios/Settings.bundle -I../../../ios/build/Build -I../../../ios/build/Logs -I../../../ios/F8v2/Images.xcassets -I../../../ios/Pods/Bolts -I../../../ios/Pods/FBSDKCoreKit -I../../../ios/Pods/FBSDKLoginKit -I../../../ios/Pods/FBSDKShareKit -I../../../ios/Pods/Headers -I../../../ios/Pods/Local\ Podspecs -I../../../ios/Pods/Target\ Support\ Files -I../../../ios/build/Logs/Build -I../../../ios/F8v2/Images.xcassets/AppIcon.appiconset -I../../../ios/Pods/Bolts/Bolts -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit -I../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit -I../../../ios/Pods/FBSDKShareKit/FBSDKShareKit -I../../../ios/Pods/Headers/Private -I../../../ios/Pods/Headers/Public -I../../../ios/Pods/Target\ Support\ Files/Bolts -I../../../ios/Pods/Target\ Support\ Files/CodePush -I../../../ios/Pods/Target\ Support\ Files/FBSDKCoreKit -I../../../ios/Pods/Target\ Support\ Files/FBSDKLoginKit -I../../../ios/Pods/Target\ Support\ Files/FBSDKShareKit -I../../../ios/Pods/Target\ Support\ Files/Pods-F8v2 -I../../../ios/Pods/Target\ Support\ Files/React -I../../../ios/Pods/Target\ Support\ Files/react-native-fbsdk -I../../../ios/Pods/Bolts/Bolts/Common -I../../../ios/Pods/Bolts/Bolts/iOS -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit -I../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit -I../../../ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit -I../../../ios/Pods/Headers/Private/Bolts -I../../../ios/Pods/Headers/Private/CodePush -I../../../ios/Pods/Headers/Private/FBSDKCoreKit -I../../../ios/Pods/Headers/Private/FBSDKLoginKit -I../../../ios/Pods/Headers/Private/FBSDKShareKit -I../../../ios/Pods/Headers/Private/React -I../../../ios/Pods/Headers/Private/react-native-fbsdk -I../../../ios/Pods/Headers/Public/Bolts -I../../../ios/Pods/Headers/Public/CodePush -I../../../ios/Pods/Headers/Public/FBSDKCoreKit -I../../../ios/Pods/Headers/Public/FBSDKLoginKit -I../../../ios/Pods/Headers/Public/FBSDKShareKit -I../../../ios/Pods/Headers/Public/React -I../../../ios/Pods/Headers/Public/react-native-fbsdk -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal_NoARC -I../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal -I../../../ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Internal -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit -I../../../ios/Pods/Headers/Private/FBSDKShareKit/FBSDKShareKit -I../../../ios/Pods/Headers/Public/FBSDKCoreKit/FBSDKCoreKit -I../../../ios/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/AppEvents -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/AppLink -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Base64 -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Cryptography -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/ErrorRecovery -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Network -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/ServerConfiguration -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/UI -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal -I../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI/ProtocolVersions -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/AppEvents -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/AppLink -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Base64 -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Cryptography -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/ErrorRecovery -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Network -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/ServerConfiguration -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/UI -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog -I../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI/ProtocolVersions -I/var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/DerivedSources/x86_64 -I/var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/DerivedSources -F/var/IOS/f8app/ios/build/Build/Products/Debug-iphonesimulator -F/Users/wuyuan/Documents/FacebookSDK -F../../../ios -F../../../ios/build -F../../../ios/F8v2 -F../../../ios/F8v2.xcworkspace -F../../../ios/F8v2Tests -F../../../ios/Pods -F../../../ios/Settings.bundle -F../../../ios/build/Build -F../../../ios/build/Logs -F../../../ios/F8v2/Images.xcassets -F../../../ios/Pods/Bolts -F../../../ios/Pods/FBSDKCoreKit -F../../../ios/Pods/FBSDKLoginKit -F../../../ios/Pods/FBSDKShareKit -F../../../ios/Pods/Headers -F../../../ios/Pods/Local\ Podspecs -F../../../ios/Pods/Target\ Support\ Files -F../../../ios/build/Logs/Build -F../../../ios/F8v2/Images.xcassets/AppIcon.appiconset -F../../../ios/Pods/Bolts/Bolts -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit -F../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit -F../../../ios/Pods/FBSDKShareKit/FBSDKShareKit -F../../../ios/Pods/Headers/Private -F../../../ios/Pods/Headers/Public -F../../../ios/Pods/Target\ Support\ Files/Bolts -F../../../ios/Pods/Target\ Support\ Files/CodePush -F../../../ios/Pods/Target\ Support\ Files/FBSDKCoreKit -F../../../ios/Pods/Target\ Support\ Files/FBSDKLoginKit -F../../../ios/Pods/Target\ Support\ Files/FBSDKShareKit -F../../../ios/Pods/Target\ Support\ Files/Pods-F8v2 -F../../../ios/Pods/Target\ Support\ Files/React -F../../../ios/Pods/Target\ Support\ Files/react-native-fbsdk -F../../../ios/Pods/Bolts/Bolts/Common -F../../../ios/Pods/Bolts/Bolts/iOS -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit -F../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit -F../../../ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit -F../../../ios/Pods/Headers/Private/Bolts -F../../../ios/Pods/Headers/Private/CodePush -F../../../ios/Pods/Headers/Private/FBSDKCoreKit -F../../../ios/Pods/Headers/Private/FBSDKLoginKit -F../../../ios/Pods/Headers/Private/FBSDKShareKit -F../../../ios/Pods/Headers/Private/React -F../../../ios/Pods/Headers/Private/react-native-fbsdk -F../../../ios/Pods/Headers/Public/Bolts -F../../../ios/Pods/Headers/Public/CodePush -F../../../ios/Pods/Headers/Public/FBSDKCoreKit -F../../../ios/Pods/Headers/Public/FBSDKLoginKit -F../../../ios/Pods/Headers/Public/FBSDKShareKit -F../../../ios/Pods/Headers/Public/React -F../../../ios/Pods/Headers/Public/react-native-fbsdk -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal_NoARC -F../../../ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal -F../../../ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Internal -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit -F../../../ios/Pods/Headers/Private/FBSDKShareKit/FBSDKShareKit -F../../../ios/Pods/Headers/Public/FBSDKCoreKit/FBSDKCoreKit -F../../../ios/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/AppEvents -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/AppLink -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Base64 -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Cryptography -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/ErrorRecovery -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Network -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/ServerConfiguration -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/UI -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal -F../../../ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI/ProtocolVersions -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/AppEvents -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/AppLink -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Base64 -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Cryptography -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/ErrorRecovery -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/Network -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/ServerConfiguration -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/UI -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog -F../../../ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit/Internal/BridgeAPI/ProtocolVersions -MMD -MT dependencies -MF /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareDialog.d --serialize-diagnostics /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareDialog.dia -c /var/IOS/f8app/node_modules/react-native-fbsdk/iOS/RCTFBSDK/share/RCTFBSDKShareDialog.m -o /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareDialog.o

=== BUILD TARGET React OF PROJECT Pods WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **

The following build commands failed:
	CompileC /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.o BVLinearGradient/BVLinearGradientManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /var/IOS/f8app/ios/build/Build/Intermediates/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradient.o BVLinearGradient/BVLinearGradient.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /var/IOS/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Bolts.build/Objects-normal/x86_64/BFAppLinkNavigation.o Bolts/Bolts/iOS/BFAppLinkNavigation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /var/IOS/f8app/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareDialog.o RCTFBSDK/share/RCTFBSDKShareDialog.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/private/var/IOS/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (/private/var/IOS/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /private/var/IOS/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/private/var/IOS/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/private/var/IOS/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/private/var/IOS/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/private/var/IOS/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/private/var/IOS/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)

Xcode: Version 7.3.1 (7D1014)
Node: v5.3.0
react-native-cli: 1.0.0
react-native: 0.28.

**Comment by lusecond** [comment]
gcc -v

Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer//usr --with-gxx-include-dir=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.5.0

**Comment by jaggerwang** [comment]
+1

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/jagger/projects/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/react-native-fbsdk.build/Objects-normal/x86_64/RCTConvert+FBSDKSharingContent.o /Users/jagger/projects/f8app/node_modules/react-native-fbsdk/iOS/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/jagger/projects/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:486:13)
    at Object.execFileSync (child_process.js:506:13)
    at _runIOS (/Users/jagger/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /Users/jagger/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/jagger/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/jagger/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/jagger/projects/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/jagger/projects/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/jagger/projects/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by Shangyunliang** [comment]
react-native upgrade 
npm install
pod update

**Comment by jaggerwang** [comment]
Still the same:(

**Comment by Shangyunliang** [comment]
check node.js version and better update all into the latest. Good Luck!

**Comment by dstnation** [comment]
try thiis

Download directly [react-native-fbsdk.podspec](https://raw.githubusercontent.com/fbsamples/f8app/master/node_modules/react-native-fbsdk/iOS/react-native-fbsdk.podspec) into "./node_modules/react-native-fbsdk/iOS/"

then, remove pod.lock
then, pod install

**Comment by lusecond** [comment]
1.cd node_modules/react-native-fbsdk/iOS   &&  cat   react-native-fbsdk.podspec
 I found them same.@dstnation 
2.I have looked https://github.com/facebook/react-native-fbsdk/issues/125 
then,pod update
`/Users/wuyuan/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /private/var/IOS/f8app/ios in PATH, mode 040777
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk/iOS`
Downloading dependencies
Using Bolts (1.8.3)
Using CodePush (1.12.2)
Using FBSDKCoreKit (4.13.1)
Using FBSDKLoginKit (4.13.1)
Using FBSDKShareKit (4.13.1)
Using React (0.28.0)
Using react-native-fbsdk (0.2.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 13 dependencies from the Podfile and 7 total pods
installed.

[!] The `F8v2 [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-F8v2/Pods-F8v2.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `F8v2 [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-F8v2/Pods-F8v2.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.`

**Comment by lusecond** [comment]
** BUILD FAILED **

**Comment by jaggerwang** [comment]
Why is so unstable~

**Comment by dstnation** [comment]
when i was getting that error;

**i did this** ,
$ npm -i S react-native-fbsdk@0.2.2 (upgrade react-native-fbsdk version)
$ cd ios/ && rm Podfile.lock
$ pod install
...
Installing FBSDKCoreKit 4.12.0 (was 4.10.1)
Installing FBSDKLoginKit 4.12.0 (was 4.10.1)
Installing FBSDKShareKit 4.12.0 (was 4.10.1)
...

$ cd ../ && react-native run-ios
**Working well**

could you, try this from the beginning

$ git clone https://github.com/fbsamples/f8app.git &&  cd f8app/ && npm i
$ cd ios
$ pod install

**_... pod error_**
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`
...
$ wget https://raw.githubusercontent.com/fbsamples/f8app/master/node_modules/react-native-fbsdk/iOS/react-native-fbsdk.podspec -O ../node_modules/react-native-fbsdk/iOS/react-native-fbsdk.podspec
...
Downloading dependencies
Installing Bolts (1.7.0)
Using CodePush (1.12.2)
Installing FBSDKCoreKit (4.10.1)
Installing FBSDKLoginKit (4.10.1)
Installing FBSDKShareKit (4.10.1)
Using React (0.28.0)
Using react-native-fbsdk (0.2.1)
...

$ cd ../ && react-native run-ios

**_... build error_**
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
...

$ npm i -S react-native-fbsdk@0.2.2
$ cd ios/ && rm Podfile.lock
$ pod install 
...
Using Bolts (1.7.0)
Using CodePush (1.12.2)
Using FBSDKCoreKit (4.12.0)
Using FBSDKLoginKit (4.12.0)
Using FBSDKShareKit (4.12.0)
...

$ cd ../ && react-native run-ios

**Comment by lusecond** [comment]
react-native run-ios  ** BUILD FAILED ** again @dstnation ,but it can build and run in xcode

**Comment by henryzp** [comment]
@dstnation i try your three method，but it not work in my mac

also the error:

> Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by frantic** [comment]
This was a problem with [`react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk), the podspec was missing. Should be fixed now, I'll upgrade package.json soon.

**Comment by bobzhen** [comment]
try upgrade/downgrade your node, may solve this problem.

**Comment by alxvallejo** [comment]
@frantic I'm still seeing this issue. Curious why there's no issue's tab on https://github.com/facebook/react-native-fbsdk.

First time around, I kept my version at 0.6.0, but running `react-native install react-native-fbsdk` automatically increases that to 0.6.1 and then linking that package fails on the project.

**Comment by twoducky** [comment]
Any news on this? Still getting the error.

**Comment by FloSugar** [comment]
Still getting the error as well. My nightmares are filled with **BUILD FAILED**

**Comment by codeandproduce** [comment]
any updates??
